"""initial schema

Revision ID: c5f4f82f4cfe
Revises: 
Create Date: 2026-08-07 19:22:34.217041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f4f82f4cfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('broker_accounts',
    sa.Column('login', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=128), nullable=False),
    sa.Column('broker_name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('encrypted_password', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_login'), 'broker_accounts', ['login'], unique=False)
    op.create_table('news_events',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('impact', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='newsimpact', native_enum=False, length=8), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast', sa.String(length=64), nullable=True),
    sa.Column('previous', sa.String(length=64), nullable=True),
    sa.Column('actual', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_country'), 'news_events', ['country'], unique=False)
    op.create_index(op.f('ix_news_events_event_time'), 'news_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_news_events_impact'), 'news_events', ['impact'], unique=False)
    op.create_table('telegram_subscribers',
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notify_trade_opened', sa.Boolean(), nullable=False),
    sa.Column('notify_trade_closed', sa.Boolean(), nullable=False),
    sa.Column('notify_sl_tp_hit', sa.Boolean(), nullable=False),
    sa.Column('notify_high_impact_news', sa.Boolean(), nullable=False),
    sa.Column('notify_daily_summary', sa.Boolean(), nullable=False),
    sa.Column('notify_new_setup', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_subscribers_chat_id'), 'telegram_subscribers', ['chat_id'], unique=True)
    op.create_table('trade_setups',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.Enum('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', name='timeframe', native_enum=False, length=8), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', 'NEUTRAL', name='tradedirection', native_enum=False, length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('risk_reward', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('structure_snapshot', sa.JSON(), nullable=False),
    sa.Column('ai_narrative', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'TAKEN', 'INVALIDATED', 'EXPIRED', name='setupstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_setups_symbol'), 'trade_setups', ['symbol'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('free_margin', sa.Float(), nullable=False),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_table('daily_performance',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starting_equity', sa.Float(), nullable=False),
    sa.Column('ending_equity', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('max_intraday_drawdown_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_daily_performance_account_date')
    )
    op.create_index(op.f('ix_daily_performance_account_id'), 'daily_performance', ['account_id'], unique=False)
    op.create_index(op.f('ix_daily_performance_date'), 'daily_performance', ['date'], unique=False)
    op.create_table('journal_entries',
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', 'NEUTRAL', name='tradedirection', native_enum=False, length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_percent', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Enum('WIN', 'LOSS', 'BREAKEVEN', 'PENDING', name='tradeoutcome', native_enum=False, length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('trader_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setup_id'], ['trade_setups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_account_id'), 'journal_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_mt5_ticket'), 'journal_entries', ['mt5_ticket'], unique=False)
    op.create_index(op.f('ix_journal_entries_setup_id'), 'journal_entries', ['setup_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_symbol'), 'journal_entries', ['symbol'], unique=False)
    op.create_table('risk_settings',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=False),
    sa.Column('max_daily_loss_percent', sa.Float(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('max_drawdown_percent', sa.Float(), nullable=False),
    sa.Column('breakeven_trigger_r', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('screenshot_analyses',
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('symbol_hint', sa.String(length=32), nullable=True),
    sa.Column('detected_trend', sa.String(length=32), nullable=True),
    sa.Column('detected_support', sa.JSON(), nullable=False),
    sa.Column('detected_resistance', sa.JSON(), nullable=False),
    sa.Column('suggested_entry', sa.Float(), nullable=True),
    sa.Column('suggested_stop_loss', sa.Float(), nullable=True),
    sa.Column('suggested_take_profit', sa.Float(), nullable=True),
    sa.Column('mistakes', sa.JSON(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('full_report', sa.Text(), nullable=False),
    sa.Column('raw_model_response', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshot_analyses_journal_entry_id'), 'screenshot_analyses', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshot_analyses_journal_entry_id'), table_name='screenshot_analyses')
    op.drop_table('screenshot_analyses')
    op.drop_table('risk_settings')
    op.drop_index(op.f('ix_journal_entries_symbol'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_setup_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_mt5_ticket'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_account_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_daily_performance_date'), table_name='daily_performance')
    op.drop_index(op.f('ix_daily_performance_account_id'), table_name='daily_performance')
    op.drop_table('daily_performance')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_trade_setups_symbol'), table_name='trade_setups')
    op.drop_table('trade_setups')
    op.drop_index(op.f('ix_telegram_subscribers_chat_id'), table_name='telegram_subscribers')
    op.drop_table('telegram_subscribers')
    op.drop_index(op.f('ix_news_events_impact'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_event_time'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_country'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_broker_accounts_login'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
